# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
