# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='subject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='subject',
            name='slideshow',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
