# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='users.Subject'),
        ),
    ]
