# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obituary_image', models.CharField(max_length=300, null=True)),
                ('subject_description', models.CharField(max_length=1000, null=True)),
                ('subject_family', models.CharField(max_length=1000, null=True)),
                ('funeral_details', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Funeral',
        ),
        migrations.AddField(
            model_name='friend',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='gofundme',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='obituary',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obituaries', to='users.Subject'),
        ),
    ]
