# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180223_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obituary',
            old_name='funeral_details',
            new_name='funeral_information',
        ),
        migrations.AddField(
            model_name='condolence',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
