# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180223_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='message',
            new_name='birthday',
        ),
    ]
